"use client";
import useSWR from "swr";
import { api, VariantInfo } from "@/lib/api";

const WORKSPACE_ID = process.env.NEXT_PUBLIC_WORKSPACE_ID || "";

const ROLE_META = {
  champion:   { icon: "🏆", label: "Champion", weight: "60%", desc: "Best performer, gets most traffic" },
  challenger: { icon: "⚔️",  label: "Challenger", weight: "25%", desc: "2nd best, keeps pressure on champion" },
  explorer:   { icon: "🔬", label: "Explorer", weight: "15%", desc: "Testing new hypothesis — auto-replaced at 50 samples" },
};

const CONFIDENCE_STYLE = {
  high:   "text-green-400",
  medium: "text-yellow-400",
  low:    "text-zinc-500",
};

function VariantCard({ role, variant }: { role: "champion" | "challenger" | "explorer"; variant: VariantInfo }) {
  const meta = ROLE_META[role];
  const pct = (variant.positive_rate * 100).toFixed(1);
  const progress = Math.min(100, (variant.sent / 50) * 100);

  return (
    <div className="rounded-xl bg-zinc-900 border border-zinc-800 p-5 flex flex-col gap-3">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xl">{meta.icon}</span>
          <div>
            <div className="font-semibold text-zinc-100 text-sm">{meta.label}</div>
            <div className="text-xs text-zinc-500">{meta.weight} of traffic</div>
          </div>
        </div>
        {variant.version && (
          <span className="text-xs text-zinc-500 bg-zinc-800 px-2 py-0.5 rounded-full">
            v{variant.version}
          </span>
        )}
      </div>

      {/* Stats */}
      {variant.sent > 0 ? (
        <div className="grid grid-cols-3 gap-2 text-center">
          <div>
            <div className="text-lg font-bold text-violet-400">{pct}%</div>
            <div className="text-xs text-zinc-500">positive rate</div>
          </div>
          <div>
            <div className="text-lg font-bold text-zinc-100">{variant.sent}</div>
            <div className="text-xs text-zinc-500">sent</div>
          </div>
          <div>
            <div className={`text-sm font-medium capitalize ${CONFIDENCE_STYLE[variant.confidence]}`}>
              {variant.confidence}
            </div>
            <div className="text-xs text-zinc-500">confidence</div>
          </div>
        </div>
      ) : (
        <div className="text-xs text-zinc-600 italic">No data yet</div>
      )}

      {/* Progress to 50 samples (explorer only) */}
      {role === "explorer" && (
        <div>
          <div className="flex justify-between text-xs text-zinc-500 mb-1">
            <span>{variant.sent}/50 samples</span>
            {variant.samples_needed > 0 && <span>{variant.samples_needed} until auto-refresh</span>}
            {variant.samples_needed === 0 && <span className="text-yellow-400">Ready to refresh</span>}
          </div>
          <div className="h-1.5 bg-zinc-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-violet-500 rounded-full transition-all"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>
      )}

      {/* Content preview */}
      {variant.content_preview && (
        <p className="text-xs text-zinc-600 line-clamp-3 italic border-t border-zinc-800 pt-3">
          {variant.content_preview}
        </p>
      )}

      {/* Created by */}
      {variant.created_by && (
        <div className="text-xs text-zinc-600">
          {variant.created_by === "claude_optimizer" ? "✨ Generated by optimizer" : `Created by: ${variant.created_by}`}
        </div>
      )}
    </div>
  );
}

function AxisSection({ title, variants }: {
  title: string;
  variants: { champion: VariantInfo; challenger: VariantInfo; explorer: VariantInfo };
}) {
  return (
    <div>
      <h2 className="text-sm font-semibold text-zinc-400 uppercase tracking-wider mb-3">{title}</h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <VariantCard role="champion" variant={variants.champion} />
        <VariantCard role="challenger" variant={variants.challenger} />
        <VariantCard role="explorer" variant={variants.explorer} />
      </div>
    </div>
  );
}

export default function VariantsPage() {
  const { data: workspaces } = useSWR("workspaces", () => api.getWorkspaces());
  const wsId = workspaces?.[0]?.id || WORKSPACE_ID;

  const { data, isLoading, mutate } = useSWR(
    wsId ? `variants:${wsId}` : null,
    () => api.getVariantStatus(wsId),
    { refreshInterval: 30000 }
  );

  const [running, setRunning] = React.useState(false);

  async function handleRunOptimizer() {
    if (!wsId) return;
    setRunning(true);
    try {
      await api.triggerOptimization(wsId);
      setTimeout(() => { mutate(); setRunning(false); }, 3000);
    } catch {
      setRunning(false);
    }
  }

  const lastRun = data?.last_optimization;

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-10">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-zinc-100">A/B Testing</h1>
          <p className="text-sm text-zinc-500 mt-1">
            Champion/Challenger/Explorer — optimizer runs nightly, promotes winners automatically
          </p>
        </div>
        <button
          onClick={handleRunOptimizer}
          disabled={running || !wsId}
          className="px-4 py-2 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white text-sm font-medium rounded-lg transition-colors"
        >
          {running ? "Running..." : "Run Optimizer Now"}
        </button>
      </div>

      {isLoading && (
        <div className="text-zinc-500 text-sm">Loading variant data...</div>
      )}

      {data && (
        <>
          <AxisSection title="Email Body Variants" variants={data.body} />
          <AxisSection title="Subject Line Variants" variants={data.subject} />

          {/* Last optimization */}
          {lastRun && (
            <div className="rounded-xl bg-zinc-900 border border-zinc-800 p-6">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-semibold text-zinc-300">Last Optimizer Run</h3>
                <div className="flex items-center gap-3">
                  <span className={`text-xs px-2 py-0.5 rounded-full ${
                    lastRun.status === "completed" ? "bg-green-900 text-green-400" :
                    lastRun.status === "needs_review" ? "bg-yellow-900 text-yellow-400" :
                    "bg-zinc-800 text-zinc-400"
                  }`}>
                    {lastRun.status}
                  </span>
                  <span className="text-xs text-zinc-500">
                    {new Date(lastRun.ran_at).toLocaleDateString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}
                  </span>
                </div>
              </div>
              {lastRun.claude_reasoning && (
                <p className="text-sm text-zinc-400 leading-relaxed whitespace-pre-line">
                  {lastRun.claude_reasoning.slice(0, 600)}{lastRun.claude_reasoning.length > 600 ? "..." : ""}
                </p>
              )}
            </div>
          )}
        </>
      )}

      {!isLoading && !data && (
        <div className="rounded-xl bg-zinc-900 border border-zinc-800 p-8 text-center">
          <p className="text-zinc-500 text-sm">No variant data yet. Complete onboarding to start the pipeline.</p>
        </div>
      )}
    </div>
  );
}

// Need React for useState
import React from "react";
